package org.crabcore.u1control.slicing

import java.nio.file.Files
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Test

class GcodeFirstLayerGuardTest {
  @Test
  fun clampsModalAndExplicitFeedratesOnlyDuringFirstLayerExtrusion() {
    withGcode(
      """
      ; generated by OrcaSlicer
      M83
      ;LAYER_CHANGE
      G1 X0 Y0 F30000
      G1 X10 Y0 E0.4 F3000 ; wall
      G1 F6300
      G1 X20 Y0 E0.4 ; bottom surface
      G1 X30 Y0 E0.4 F7200 ; explicit fast infill
      G1 X35 Y0 E-0.8 F9000 ; retract
      ;LAYER_CHANGE
      G1 X40 Y0 E0.4 F7200 ; later layer
      """.trimIndent(),
    ) { file ->
      val result = GcodeFirstLayerGuard.apply(file.toString())
      val output = readText(file)

      assertTrue(result.success)
      assertEquals(2, result.rewrittenMoves)
      assertTrue(output.startsWith("; helix_first_layer_feedrate_limit = 50 mm/s\n"))
      assertTrue(output.contains("G1 X20 Y0 E0.4 F3000 ; bottom surface"))
      assertTrue(output.contains("G1 X30 Y0 E0.4 F3000 ; explicit fast infill"))
      assertTrue(output.contains("G1 X35 Y0 E-0.8 F9000 ; retract"))
      assertTrue(output.contains("G1 X40 Y0 E0.4 F7200 ; later layer"))
    }
  }

  @Test
  fun supportsAbsoluteExtrusionAndNumberedLayerComments() {
    withGcode(
      """
      M82
      G92 E0
      ;LAYER:0
      G1 X10 E1.0 F6000
      G1 X20 E0.5 F9000
      G1 X30 E1.5 F6000
      ;LAYER:1
      G1 X40 E2.0 F6000
      """.trimIndent(),
    ) { file ->
      val result = GcodeFirstLayerGuard.apply(file.toString())
      val output = readText(file)

      assertTrue(result.success)
      assertEquals(2, result.rewrittenMoves)
      assertTrue(output.contains("G1 X10 E1.0 F3000"))
      assertTrue(output.contains("G1 X20 E0.5 F9000"))
      assertTrue(output.contains("G1 X30 E1.5 F3000"))
      assertTrue(output.contains("G1 X40 E2.0 F6000"))
    }
  }

  @Test
  fun applyingGuardTwiceDoesNotRewriteAgain() {
    withGcode(
      """
      M83
      ;LAYER_CHANGE
      G1 X10 E0.5 F6000
      ;LAYER_CHANGE
      """.trimIndent(),
    ) { file ->
      val first = GcodeFirstLayerGuard.apply(file.toString())
      val afterFirst = readText(file)
      val second = GcodeFirstLayerGuard.apply(file.toString())

      assertTrue(first.success)
      assertTrue(second.success)
      assertTrue(second.alreadyApplied)
      assertEquals(afterFirst, readText(file))
    }
  }

  @Test
  fun failsClosedWhenLayerMarkersAreMissing() {
    withGcode("M83\nG1 X10 E0.5 F6000") { file ->
      val original = readText(file)
      val result = GcodeFirstLayerGuard.apply(file.toString())

      assertFalse(result.success)
      assertEquals(original, readText(file))
    }
  }

  private fun withGcode(contents: String, block: (java.nio.file.Path) -> Unit) {
    val file = Files.createTempFile("helix-first-layer-", ".gcode")
    try {
      Files.write(file, "$contents\n".toByteArray(Charsets.UTF_8))
      block(file)
    } finally {
      Files.deleteIfExists(file)
    }
  }

  private fun readText(file: java.nio.file.Path): String =
    String(Files.readAllBytes(file), Charsets.UTF_8)
}
